steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/examproject-mlops/dockers', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/examproject-mlops/dockers']
timeout: 1200s
