wandb_version: 1

Model&Data:
  desc: null
  value: '{''model_name'': ''gpt2'', ''n_labels'': 2, ''input_filepath'': ''./data/raw/'',
    ''output_filepath'': ''./data/processed/'', ''seed'': 0}'
Train:
  desc: null
  value: '{''batch_size'': 128, ''batch_ratio_validation'': 0.2, ''lr'': 0.01, ''lr_scheduler'':
    ''cosine'', ''warmup_step_perc'': 0, ''epochs'': 4, ''seed'': 1234, ''optimizer_type'':
    ''adamw'', ''weight_decay'': 0.02}'
_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: huggingface
    huggingface_version: 4.15.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1642087133
    t:
      1:
      - 1
      - 5
      - 11
      2:
      - 1
      - 5
      - 11
      3:
      - 1
      - 16
      4: 3.9.7
      5: 0.12.9
      6: 4.15.0
      8:
      - 5
